### Indeed.ca Internship Summary

git@github.com:jodiqiao/internship_analysis.git

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("sept_final_scrape.csv", usecols = ['job_title','company_name','summary'])

In [11]:
# summary text give insight to what qualifications are needed for what job?
# qualifications different between companies even if job title similar?
# company-specific preference of qualifications?

In [4]:
import nltk
#nltk.download()

In [13]:
sentence = df['summary'][0]

In [38]:
# test
tokens = nltk.word_tokenize(sentence)

In [ ]:
# https://www.digitalocean.com/community/tutorials/how-to-work-with-language-data-in-python-3-using-the-natural-language-toolkit-nltk
# https://blog.algorithmia.com/introduction-natural-language-processing-nlp
# https://www.kaggle.com/itratrahman/nlp-tutorial-using-python

In [5]:
from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split, KFold
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from matplotlib import pyplot as plt
# import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [33]:
# https://stackoverflow.com/questions/29523254/python-remove-stop-words-from-pandas-dataframe
# compare nltk v sklearn stopwords
# Import stopwords with nltk.

# from nltk.corpus import stopwords
# stop = stopwords.words('english')

In [28]:
# np.array(stop)
# print("Number of stopwords: ", len(stop))

Number of stopwords:  179

In [6]:
from sklearn.feature_extraction import text
stop = text.ENGLISH_STOP_WORDS

In [7]:
np.array(stop)
print("Number of stopwords: ", len(stop))

# i like this one better

Number of stopwords:  318

In [8]:
# https://pythonhealthcare.org/2018/12/14/101-pre-processing-data-tokenization-stemming-and-removal-of-stop-words/
# tokenization, stemming, and removal of stop words
# i don't think i'm going to do sentiment analysis... but it's interesting
# convert to lower case

df['job_title'] = df['job_title'].str.lower()
df['company_name'] = df['company_name'].str.lower()
df['summary'] = df['summary'].str.lower()

In [9]:
import string

In [28]:
# tokenize, remove punctuation, remove stopwords

def pre_process(row):
    data_in_row = row['summary']
    tokens = nltk.word_tokenize(data_in_row) # is a list of tokens
    #tokens = nltk.word_tokenize(row)
    # taken only words (not punctuation)
    no_punc_no_stop = []
    for i in range(len(tokens)):
        if "/" in tokens[i]:
            # https://stackoverflow.com/questions/9797357/dividing-a-string-at-various-punctuation-marks-using-split
            temp = tokens[i].replace('/',' ').replace('-',' ').split() # this split up web/front, coop/-intern; remove "/","-" keep both wrds
            for a in temp:
                if tokens[i] not in stop:
                    no_punc_no_stop.append(a)
        if tokens[i].isalpha() and tokens[i] != "r" and tokens[i] != "d" and tokens[i] not in stop: # capture text that isn't 'r' or '&' or 'd'
            no_punc_no_stop.append(tokens[i])
        elif tokens[i].isalpha() and tokens[i] == "r": # idk what other words could become just an r
            if tokens[i+1] == "&" and tokens[i+2] == "d": # r & d
                no_punc_no_stop.append("r&d")
                i += 2
            else:
                continue
        
    return no_punc_no_stop

# df['summary'] = df.apply(pre_process, axis=1)

In [31]:
# df['job_title'] = df.apply(pre_process, axis=1)
# df['summary'] = df.apply(pre_process, axis=1)

In [30]:
df

,job_title,company_name,summary
0,"[summer, intern, data, science, engineering]",hsbc bank canada,"[building, changing, predictive, analytical, s..."
1,"[student, intern]",skyworks,"[strong, data, analysis, skill, support, pes, ..."
2,"[data, scientist, intern]",geotab,"[data, scientist, intern, work, alongside, tea..."
3,"[data, engineer, omnia, ai, co, op, intern, wi...",deloitte,"[fascinated, data, structures, data, models, d..."
4,"[data, science, intern, winter, toronto]",intact,"[currently, looking, interns, data, lab, r&d, ..."
5,"[data, insight, specialist, co, op, intern]",general motors,"[data, insight, specialist, assist, warranty, ..."
6,"[data, analyst, intern]",upfeat media inc.,"[looking, data, analyst, intern, join, rapidly..."
7,"[intern, data, science]",rs energy group,"[analyze, interpret, heterogeneous, data, trou..."
8,"[instructional, writer, data, science, intern]",geotab,"[geotab, seeking, intern, immediately, contrib..."
9,"[op, intern, photonics, networking]",ciena,"[autonomous, photonic, networks, team, respons..."
10,"[applied, research, lab, intern]",ch four biogas inc.,"[perform, sample, analysis, collect, data, cur..."
11,"[business, support, intern, data, analytics]",geotab,"[geotab, actively, seeking, business, support,..."
12,"[analyst, strategic, operational, risk, winter...",deloitte,"[advisory, service, line, helps, organizations..."
13,"[associate, consultant, intern, data, services...",mastercard,"[associate, consultant, intern, data, services..."
14,"[student, intern, customer, data, analyst]",celestica,"[product, data, management, global, business, ..."
15,"[research, intern, toronto, waterloo]",google,"[creating, experiments, prototyping, implement..."
16,"[data, scientist, internship, opportunities]",nestlé canada inc.,"[data, scientist, intern, explore, data, answe..."
17,"[op, intern, data, analytics]",ciena,"[data, modeling, data, structures, algorithms,..."
18,"[analytics, data, science, co, op, intern]",td bank,"[office, chief, data, officer, experience, dat..."
19,"[brand, management, summer, intern]",procter and gamble,"[additionally, use, historical, data, intern, ..."
20,"[accountant, intern]",rdm disposal inc.,"[compile, data, compute, charges, prepare, inv..."
21,"[summer, intern, data, science, engineering]",hsbc bank canada,"[building, changing, predictive, analytical, s..."
22,"[student, intern]",skyworks,"[strong, data, analysis, skill, support, pes, ..."
23,"[intern, opportunities, students, user, experi...",microsoft,"[knowledge, methods, gathering, analyzing, ux,..."
24,"[web, front, end, developer, intern]",geotab,"[successful, role, individual, passionate, dev..."
25,"[associate, managing, consultant, intern, data...",mastercard,"[experience, using, data, analysis, querying, ..."
26,"[python, developer, intern]",geotab,"[work, closely, data, engineering, team, devel..."
27,"[genuine, analyst, intern]",autodesk,"[analyze, piracy, trends, usage, data, summari..."
28,"[developer, intern]",geotab,"[receive, detailed, data, metrics, millions, v..."
29,"[software, developer, intern, bs, summer]",google,"[experience, data, structures, algorithms, com..."
...,...,...,...
946,"[developer, enterprise, architecture]",td bank,"[tell, story, unnoticed, explain, winning, can..."
947,"[software, developer]",nanalysis scientific corp,"[nanalysis, global, supplier, portable, nuclea..."
948,"[enterprise, enabling, technology, solutions, ...",td bank,"[tell, story, unnoticed, explain, winning, can..."
949,"[embedded, test, software, engineer]",garmin,"[embedded, test, software, engineer, cochrane,..."
950,"[intern, analyst, total, fund, management, mon...",ontario teachers' pension plan,"[opportunity, january, april, total, fund, man..."
951,"[automation, monitoring, support, analyst, inn...",td bank,"[td, description, tell, story, unnoticed, expl..."
952,"[software, testing, intern, stagiaire, en, tes...",nuance,"[company, overview, présentation, l, entrepris..."
953,"[intern, administrator]",atira development society,"[exciting, opportunity, exists, intern, sysadm..."
954,"[software, developer, intern, développeur, log...",nuance,"[company, overview, présentation, l, entrepris..."
955,"[intern, analyst, digital, innovation]",psp investments,"[intern, analyst, digital, innovation, ll, exp..."
956,"[administrator, unpaid, intern]",openconcept consulting inc.,"[scripting, languages, including, bash, php, r..."
957,"[software, tester, sam]",nokia,"[software, tester, sam, summer, op, network, m..."
958,"[op, intern, blue, planet, analytics]",ciena,"[work, team, build, leading, edge, network, ma..."
959,"[op, intern, blue, planet, network, management]",ciena,"[work, team, developers, build, leading, edge,..."
960,"[software, test, intern, montreal, r&d, center...",hikvision usa inc.,"[working, team, solution, specialists, project..."
961,"[software, test, intern, montreal, r&d, center]",hikvision canada inc.,"[working, team, solution, specialists, project..."
962,"[op, intern, data, analytics]",ciena,"[aider, l, ingénieur, e, principal, e, en, ana..."
963,"[software, test, intern, montreal, r&d, center...",hikvision,"[working, team, solution, specialists, project..."
964,"[op, intern, photonic, systems, test, engineer]",ciena,"[l, équipe, tests, et, mesures, est, responsab..."
965,"[intern, ecommerce, java, software, developer]",sap,"[collaborating, developers, testers, team, mem..."
966,"[op, intern, data, analytics]",ciena,"[aider, l, ingénieur, e, principal, e, en, ana..."
967,"[user, interface, ui, design, intern, stagiair...",nuance,"[intern, help, designers, create, user, experi..."
968,"[software, tester, sam]",nokia,"[engineering, computer, science, student, regi..."
969,"[op, intern, data, analytics]",ciena,"[help, senior, engineers, code, analytics, alg..."
970,"[tester, qa, month]",td bank,"[td, testing, quality, assurance, qa, covers, ..."
971,"[user, interface, ui, design, intern, stagiair...",nuance,"[intern, help, designers, create, user, welcom..."
972,"[software, tester, sam]",nokia,"[software, tester, sam, summer, op, network, m..."
973,"[op, intern, data, analytics]",ciena,"[aider, l, ingénieur, e, principal, e, en, ana..."
974,"[tester, qa, month]",td bank,"[explain, winning, td, crave, meaningful, work..."
975,"[intern, ecommerce, java, software, developer]",sap,"[collaborating, developers, testers, team, int..."

In [17]:
b = identify_tokens(df['summary'][957])

In [18]:
b

['software',
 'tester',
 'sam',
 'summer',
 'op',
 'network',
 'management',
 'business',
 'unit',
 'nokia',
 'ip',
 'division',
 'recruiting',
 'highly',
 'motivated',
 'software',
 'testers']

In [23]:
# test stemming
# from nltk.stem import PorterStemmer
# stemming = PorterStemmer()
# my_list = ['frightening', 'frightened', 'frightens']
# Using a Python list comprehension method to apply to all words in my_list
# print ([stemming.stem(word) for word in my_list])

In [22]:
# print ([stemming.stem(word) for word in b])
# output :
# ['softwar', 'tester', 'sam', 'summer', 'op', 'network', 'manag', 'busi',
# 'unit', 'nokia', 'ip', 'divis', 'recruit', 'highli', 'motiv', 'softwar', 'tester']
# no stemming, this is not great